name: "GitHub Action for flyctl"
description: "Wraps the flyctl CLI tool to enable deploying and managing Fly apps"
author: Fly
branding:
  icon: "upload-cloud"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"
